cities/urls.py
from django.contrib import admin
from django.urls import path
from cities.views import *

urlpatterns = [
    # path('', home, name='home'),
    path('', CityListView.as_view(), name='home'),
    path('detail/<int:pk>/', CityDetailView.as_view(), name='detail'),
    path('add/', CityCreateView.as_view(), name='create'),
    path('update/<int:pk>/', CityUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', CityDeleteView.as_view(), name='delete'),
]

routes/models.py
from django.core.exceptions import ValidationError
from django.db import models

from cities.models import City


class Route(models.Model):
    objects = None
    name = models.CharField(max_length=50, unique=True,
                            verbose_name='Название маршрута')
    travel_times = models.PositiveSmallIntegerField(verbose_name='Общее время в пути (час)')
    # поле для определения связи с таблицей City
    # on_delete=models.CASCADE удаляет все связанные записи в других таблицах
    # on_delete=models.PROTECT не сможем удалить запись до тех пор пока она связана с другими таблицами
    # on_delete=models.SET_NULL при удалении записи, значение устанавливается в NULL,
    # обязательные параметры:
    #   null=True, blank=True
    from_city = models.ForeignKey(City, on_delete=models.CASCADE,
                                  # null=True, blank=True,
                                  related_name='route_from_city_set',
                                  verbose_name='Из какого города'
                                  )
    to_city = models.ForeignKey('cities.City', on_delete=models.CASCADE,
                                related_name='route_to_city_set',
                                verbose_name='В какой город'
                                )
    trains = models.ManyToManyField('trains.Train', verbose_name='Список поездов')

    def __str__(self):
        return f'Маршрут :{self.name} из города {self.from_city}'

    class Meta:
        verbose_name = 'Маршрут'
        verbose_name_plural = 'Маршруты'
        ordering = ['travel_times']

templates/about.html
{% extends 'base.html' %}
{% block title %}About{% endblock %}
{% block content %}
<h1> Hello {{name}}! </h1>
{% endblock %}

templates/base.html
{% url 'cities:home' as cities_home_url %}
{% url 'cities:create' as cities_create_url %}
{% url 'trains:home' as trains_home_url %}
{% url 'trains:create' as trains_create_url %}
{% url 'list' as route_list %}
{% url 'detail' as route_detail %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light container" style="background-color: #e3f2fd;">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home'%}">Поиск маршрута</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link {% if request.path == cities_home_url %} active {% endif %}"
                       aria-current="page"
                       href="{% url 'cities:home'%}">Города</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == trains_home_url %} active {% endif %}"
                       aria-current="page"
                       href="{% url 'trains:home'%}">Поезда</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == route_list %} active {% endif %}"
                       href="{% url 'list' %}">Маршруты</a>
                </li>
              {% if user.is_authenticated %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle
                {% if request.path == cities_create_url or request.path == trains_create_url %} active {% endif %}"
                   href="#" id="navbarDropdownMenuLink" role="button"
                   data-bs-toggle="dropdown" aria-expanded="false">
                    Добавить
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <li><a class="dropdown-item" href="{% url 'cities:create' %}">Новый город</a></li>
                    <li><a class="dropdown-item" href="{% url 'trains:create' %}">Новый поезд</a></li>
                </ul>
              {% else %}
                    <li class="nav-item dropdown" >
                        <a class="nav-link disabled" href="">Добавить</a>
                    </li>
              {% endif %}
              </li>
             {% if not user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link "
                   href="{% url 'accounts:login' %}">Войти</a>
              </li>
              <li class="nav-item">
                <a class="nav-link "
                   href="{% url 'accounts:register' %}">Регистрация</a>
              </li>
             {% else %}
              <li class="nav-item">
                <a class="nav-link "
                   href="{% url 'accounts:logout' %}">Выйти</a>
              </li>
             {% endif %}
             </ul>
        </div>
    </div>
</nav>
<div class="continer">
    <div class="row">
        <div class="col-md-8 mx-auto my-4">
            {% if messages %}
            {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% else %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endif %}
            {% endfor %}
            {% endif %}
        </div>
    </div>
</div>
<div class="container">
    {% block content %} {% endblock %}
</div>
<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
        crossorigin="anonymous"></script>
<!--<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>-->
<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
-->
<script>
    $(document).ready(function() {
        $('.js-example-basic-single').select2();
        $('.js-example-basic-multiple').select2();
    });

</script>
</body>
</html>

templates/form.html
<div class="row">
    <div class="col-md-4">
        <form action="{{ action }}" method="post"> {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">{{ button }}</button>
        </form>
    </div>
</div></html>

templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
<h1> Hello {{name}}! </h1>
{% endblock %}